/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_log_2eproto__INCLUDED
#define PROTOBUF_C_log_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _LogEntry LogEntry;
typedef struct _LogEntry__Origin LogEntry__Origin;
typedef struct _LogEntry__Origin__Attribute LogEntry__Origin__Attribute;


/* --- enums --- */


/* --- messages --- */

struct  _LogEntry__Origin__Attribute
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define LOG_ENTRY__ORIGIN__ATTRIBUTE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&log_entry__origin__attribute__descriptor) \
    , NULL, NULL }


struct  _LogEntry__Origin
{
  ProtobufCMessage base;
  int32_t pid;
  int32_t gid;
  int32_t uid;
  char *group;
  char *user;
  size_t n_attributes;
  LogEntry__Origin__Attribute **attributes;
};
#define LOG_ENTRY__ORIGIN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&log_entry__origin__descriptor) \
    , 0, 0, 0, NULL, NULL, 0,NULL }


struct  _LogEntry
{
  ProtobufCMessage base;
  LogEntry__Origin *origin;
  char *line;
  int64_t timestamp;
};
#define LOG_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&log_entry__descriptor) \
    , NULL, NULL, 0 }


/* LogEntry__Origin__Attribute methods */
void   log_entry__origin__attribute__init
                     (LogEntry__Origin__Attribute         *message);
/* LogEntry__Origin methods */
void   log_entry__origin__init
                     (LogEntry__Origin         *message);
/* LogEntry methods */
void   log_entry__init
                     (LogEntry         *message);
size_t log_entry__get_packed_size
                     (const LogEntry   *message);
size_t log_entry__pack
                     (const LogEntry   *message,
                      uint8_t             *out);
size_t log_entry__pack_to_buffer
                     (const LogEntry   *message,
                      ProtobufCBuffer     *buffer);
LogEntry *
       log_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   log_entry__free_unpacked
                     (LogEntry *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*LogEntry__Origin__Attribute_Closure)
                 (const LogEntry__Origin__Attribute *message,
                  void *closure_data);
typedef void (*LogEntry__Origin_Closure)
                 (const LogEntry__Origin *message,
                  void *closure_data);
typedef void (*LogEntry_Closure)
                 (const LogEntry *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor log_entry__descriptor;
extern const ProtobufCMessageDescriptor log_entry__origin__descriptor;
extern const ProtobufCMessageDescriptor log_entry__origin__attribute__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_log_2eproto__INCLUDED */
