/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "log.pb-c.h"
void   log_entry__origin__attribute__init
                     (LogEntry__Origin__Attribute         *message)
{
  static LogEntry__Origin__Attribute init_value = LOG_ENTRY__ORIGIN__ATTRIBUTE__INIT;
  *message = init_value;
}
void   log_entry__origin__init
                     (LogEntry__Origin         *message)
{
  static LogEntry__Origin init_value = LOG_ENTRY__ORIGIN__INIT;
  *message = init_value;
}
void   log_entry__init
                     (LogEntry         *message)
{
  static LogEntry init_value = LOG_ENTRY__INIT;
  *message = init_value;
}
size_t log_entry__get_packed_size
                     (const LogEntry *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &log_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t log_entry__pack
                     (const LogEntry *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &log_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t log_entry__pack_to_buffer
                     (const LogEntry *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &log_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LogEntry *
       log_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LogEntry *)
     protobuf_c_message_unpack (&log_entry__descriptor,
                                allocator, len, data);
}
void   log_entry__free_unpacked
                     (LogEntry *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &log_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor log_entry__origin__attribute__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(LogEntry__Origin__Attribute, key),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(LogEntry__Origin__Attribute, value),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned log_entry__origin__attribute__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange log_entry__origin__attribute__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor log_entry__origin__attribute__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "LogEntry.Origin.Attribute",
  "Attribute",
  "LogEntry__Origin__Attribute",
  "",
  sizeof(LogEntry__Origin__Attribute),
  2,
  log_entry__origin__attribute__field_descriptors,
  log_entry__origin__attribute__field_indices_by_name,
  1,  log_entry__origin__attribute__number_ranges,
  (ProtobufCMessageInit) log_entry__origin__attribute__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor log_entry__origin__field_descriptors[6] =
{
  {
    "pid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(LogEntry__Origin, pid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(LogEntry__Origin, gid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uid",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(LogEntry__Origin, uid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(LogEntry__Origin, group),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(LogEntry__Origin, user),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attributes",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(LogEntry__Origin, n_attributes),
    PROTOBUF_C_OFFSETOF(LogEntry__Origin, attributes),
    &log_entry__origin__attribute__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned log_entry__origin__field_indices_by_name[] = {
  5,   /* field[5] = attributes */
  1,   /* field[1] = gid */
  3,   /* field[3] = group */
  0,   /* field[0] = pid */
  2,   /* field[2] = uid */
  4,   /* field[4] = user */
};
static const ProtobufCIntRange log_entry__origin__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor log_entry__origin__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "LogEntry.Origin",
  "Origin",
  "LogEntry__Origin",
  "",
  sizeof(LogEntry__Origin),
  6,
  log_entry__origin__field_descriptors,
  log_entry__origin__field_indices_by_name,
  1,  log_entry__origin__number_ranges,
  (ProtobufCMessageInit) log_entry__origin__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor log_entry__field_descriptors[3] =
{
  {
    "origin",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(LogEntry, origin),
    &log_entry__origin__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "line",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(LogEntry, line),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SFIXED64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(LogEntry, timestamp),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned log_entry__field_indices_by_name[] = {
  1,   /* field[1] = line */
  0,   /* field[0] = origin */
  2,   /* field[2] = timestamp */
};
static const ProtobufCIntRange log_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor log_entry__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "LogEntry",
  "LogEntry",
  "LogEntry",
  "",
  sizeof(LogEntry),
  3,
  log_entry__field_descriptors,
  log_entry__field_indices_by_name,
  1,  log_entry__number_ranges,
  (ProtobufCMessageInit) log_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
